apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
# This is where you put production-specific Vault settings later
# For example, if you want a different replica count for prod:
# patches:
#   - target:
#       kind: StatefulSet
#       name: vault
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 3
