apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/releases/cnpg-1.22.1.yaml

# force the namespace here to ensure the operator doesn't
# accidentally install into 'default'
namespace: cnpg-system
