# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustfs
  namespace: storage
spec:
  selector:
    matchLabels:
      app: rustfs # has to match .spec.template.metadata.labels

  serviceName: "rustfs"
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: rustfs
      labels:
        app: rustfs # has to match .spec.selector.matchLabels

    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rustfs
          image: ghcr.io/rustfs/rustfs:1.0.0-alpha.81
          ports:
            - containerPort: 9000
              name: rustfs
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
  volumeClaimTemplates: # this acts as a "Factory"; it creates new PVCs automatically for every replica I have
    - metadata:
        name: rustfs-data
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
