# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: storage

spec:
  type: ClusterIP
  selector:
    app: rustfs
  ports:
    - name: s3-api
      protocol: TCP
      port: 9000
      targetPort: 9000
---

