apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

helmCharts:
  - name: openbao
    releaseName: openbao
    valuesInline:
      server:
        ha:
          replicas: 1
