# ~/workspaces/homelab/infrastructure/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway-api/
#- ./cnpg/base # This points to the next level down
#- ./minio/base # You'll add this later!
