# ~/workspaces/homelab/infrastructure/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api # Points to gateway-api/kustomization.yaml
  - controllers # Points to controllers/kustomization.yaml
  - storage # oints to storage/kustomization.yaml
